cmake_minimum_required(VERSION 3.13.4)
find_package(Aspect REQUIRED HINTS ${Aspect_DIR})
DEAL_II_INITIALIZE_CACHED_VARIABLES()
project(particle_lifecycle)
add_library(coupled_lifecycle SHARED coupled.cc)
ASPECT_SETUP_PLUGIN(coupled_lifecycle)
target_link_libraries(coupled_lifecycle ${CMAKE_CURRENT_BINARY_DIR}/../bp3/libbp3_restore_150x50.release.so)
add_library(particle_streams SHARED streams.cc)
ASPECT_SETUP_PLUGIN(particle_streams)
